import SubscriptionButton from "@/components/subscription-button"
import { checkSubscription } from "@/lib/subscription"
import { Metadata } from "next"


export const metadata: Metadata = {
  title: 'Devcore AI | Settings',
  description: 'Generated by create next app',
}

const SettingPage =async () => {
  const isPro = await checkSubscription()
  return (
    <div className=" h-full p-4 space-y-2">
      <h3 className=" text-lg font-medium ">Settings</h3>
      <div className="text-muted-foreground text-sm">
        {isPro ? "You are currently on a Pro plan": "You are currently on a free plan"}
      </div>
      <SubscriptionButton isPro={isPro} />
    </div>
  )
}

export default SettingPage